language: rust

os:
  - linux
  - windows
  - osx

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

cache: cargo

script:
  - rustup component add clippy && cargo -q clippy --all --message-format short --tests -- -D warnings
  - cargo test --verbose --all
  - rustup component add rustfmt && cargo fmt --all -- --check
  - cargo doc --no-deps && cargo install cargo-deadlinks && cargo deadlinks --dir target/doc/file_store

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo install cargo-tarpaulin -f
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --ignore-tests
  fi
