language: rust

os:
  - linux
  - windows
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

install:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo -q clippy --all --message-format short --tests -- -D warnings
  - cargo test --verbose --all
  - cargo fmt --all -- --check
