language: rust

os:
  - linux
  - windows
  - osx

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - nightly

cache: cargo

install:
  - rustup component add clippy
  - rustup component add rustfmt

script:
#  - cargo -q clippy --all --message-format short --tests -- -D warnings
  - cargo test --verbose --all
  - cargo fmt --all -- --check

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo install cargo-tarpaulin -f
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
