trigger:
  - master

variables:
  default_toolchain: nightly

jobs:
  - job: clippy
    displayName: Lint code
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          rustup component add clippy
          cargo clippy --version
        displayName: Install clippy
      - script: |
          cargo -q clippy --all --all-features --message-format short --tests -- -D warnings
        displayName: Run clippy

  - job: rustfmt
    displayName: Check code formatting
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          rustup component add rustfmt
          cargo fmt --version
        displayName: Install rustfmt
      - script: |
          cargo fmt --all -- --check
        displayName: Run rustfmt

  - job: docs
    displayName: Check docs
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          cargo install cargo-deadlinks
          cargo deadlinks --version
        displayName: Install deadlinks
      - script: |
          cargo doc --no-deps
          cargo deadlinks --dir target/doc/file_store
        displayName: Run clippy

  - job: coverage
    displayName: Generate code coverate
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --version
        displayName: Install tarpaulin
      - script: |
          cargo tarpaulin --ciserver azure --coveralls $BUILD_BUILDID --ignore-tests
        displayName: Measure coverage

  - job: tests
    displayName: Run tests
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          cargo test --all --release
        displayName: Run tests
