trigger:
  - master

variables:
  default_toolchain: nightly

jobs:
  - job: clippy
    displayName: Lint code
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          rustup component add clippy
          cargo clippy --version
        displayName: Install clippy
      - script: |
          cargo -q clippy --all --all-features --message-format short --tests -- -D warnings
        displayName: Run clippy

  - job: rustfmt
    displayName: Check code formatting
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          rustup component add rustfmt
          cargo fmt --version
        displayName: Install rustfmt
      - script: |
          cargo fmt --all -- --check
        displayName: Run rustfmt

  - job: docs
    displayName: Check docs
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          cargo install cargo-deadlinks
          cargo deadlinks --version
        displayName: Install deadlinks
      - script: |
          cargo doc --no-deps
          cargo deadlinks --dir target/doc/file_store
        displayName: Run clippy

  - job: coverage
    displayName: Generate code coverate
    continueOnError: true
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(default_toolchain)
      - script: |
          cargo check --release
          cargo install cargo-tarpaulin
          cargo tarpaulin --version
        displayName: Install tarpaulin
      - script: |
          cargo tarpaulin --ciserver azure --coveralls $BUILD_BUILDID --ignore-tests
        displayName: Measure coverage
        env:
          CI_NAME: azure
          CI_BUILD_NUMBER: $(Build_BuildId)
          CI_BUILD_URL: ${{ format('{0}{1}', 'https://dev.azure.com/dtownsend0397/file-store-rs/_build/results?buildId=', variables['Build.Build_BuildId']) }}
          CI_BRANCH: $(Build.SourceBranchName)

  - job: tests
    displayName: Run tests
    continueOnError: false
    strategy:
      matrix:
        linux-nightly:
          platform: "ubuntu-16.04"
          toolchain: "nightly"
        mac-nightly:
          platform: "macos-10.13"
          toolchain: "nightly"
        windows-nightly:
          platform: "vs2017-win2016"
          toolchain: "nightly"
    pool:
      vmImage: $(platform)
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          rust_toolchain: $(toolchain)
      - script: |
          cargo test --all --release
        displayName: Run tests
