[package]
name = "storage-types"
version = "0.1.0"
authors = ["Dave Townsend <dtownsend@oxymoronical.com>"]
edition = "2018"

[dependencies]
serde = { version = "^1.0.98", features = ["derive"] }
serde_json = "^1.0.40"
percent-encoding = "^2.1.0"
