[package]
name = "fs"
version = "0.1.0"
authors = ["Dave Townsend <dtownsend@oxymoronical.com>"]
edition = "2018"

[dependencies]
file-store = { path = "../file-store" }
clap = "~2.33.0"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
