[package]
name = "cloud-fs"
version = "0.1.0"
authors = ["Dave Townsend <dtownsend@oxymoronical.com>"]
edition = "2018"

[features]
default = ["file", "b2"]
file = []
b2 = []

[dependencies]
tokio = "0.1.21"
bytes = "0.4.12"
tokio-fs = "0.1.6"

[dev-dependencies]
tempdir = "0.3.7"
