[package]
name = "file-store"
version = "0.1.0"
authors = ["Dave Townsend <dtownsend@oxymoronical.com>"]
edition = "2018"

[features]
default = ["file"]
file = ["tokio-fs"]

[dependencies]
futures-preview = { version = "=0.3.0-alpha.17", features = ["compat", "async-await", "nightly"] }
tokio = "^0.1.21"
bytes = "^0.4.12"
tokio-sync = "^0.1.6"
tokio-fs = { version = "^0.1.6", optional = true }

[dev-dependencies]
tempfile = "^3.0.8"
