name: Checks

on: [push]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-18.04
    
    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1.1.0
      with:
        rust-version: nightly-2019-09-01
        components: clippy
    - uses: actions/checkout@v1
    - name: Run clippy
      run: cargo -q clippy --all-targets --all-features --message-format short -- -D warnings

  fmt:
    name: Check code style
    runs-on: ubuntu-18.04
    
    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1.1.0
      with:
        rust-version: nightly-2019-09-01
        components: rustfmt
    - uses: actions/checkout@v1
    - name: Check coding style
      run: cargo fmt --all -- --check

  docs:
    name: Verify documentation links
    runs-on: ubuntu-18.04

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1.1.0
      with:
        rust-version: nightly-2019-09-01
    - name: Install deadlinks
      run: cargo install cargo-deadlinks
    - uses: actions/checkout@v1
    - name: Check docs
      run: cargo doc --no-deps && cargo deadlinks --dir target/doc/file_store

  coverage:
    name: Measure code coverage
    runs-on: ubuntu-18.04

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1.1.0
      with:
        rust-version: nightly-2019-09-01
    - name: Set branch name
      run: git checkout -b master
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - uses: actions/checkout@v1
    - name: Run tarpaulin
      run: cargo tarpaulin --release --ciserver azure --coveralls $COVERALLS_TOKEN --ignore-tests
      env:
        CI_NAME: github
        CI_BUILD_URL: https://github.com/FractalBrew/file-store-rs/commit/${{ github.sha }}/checks
        CI_BRANCH: master
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

  test:
    strategy:
      matrix:
        rust-toolchain: [nightly-2019-09-01]
        os: [windows-2019, ubuntu-18.04, macOS-latest]

    name: Test on ${{ matrix.os }} with rust ${{ matrix.rust-toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1.1.0
      with:
        rust-version: ${{ matrix.rust-toolchain }}
    - uses: actions/checkout@v1
    - name: Show toolchain
      run: rustup show
    - name: Run tests
      run: cargo test --all --release
