name: Checks

on: [push]

jobs:
  test:
    strategy:
      matrix:
        rust_toolchain: [nightly-2019-09-01]
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Switch toolchain
      run: rustup toolchain install ${{ matrix.rust_toolchain }} && rustup default ${{ matrix.rust_toolchain }} && rustup show
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --all --release
