name: Checks

on: [push]

jobs:
  test:
    strategy:
      matrix:
        rust-toolchain: [nightly-2019-09-01]
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v1.1.0
      with:
        rust-version: ${{ matrix.rust-toolchain }}
    - uses: actions/checkout@v1
    - name: Show toolchain
      run: rustup show
    - name: Run tests
      run: cargo test --all --release
